export 'enums.dart';
export 'typedefs.dart';

export 'time_ago/time_ago.dart';
export 'time_ago/time_ago_message.dart';
export 'constants/constants.dart';
export 'constants/assets.dart';

export 'helpers/tagging_helper.dart';
export 'helpers/text_helper.dart';

export 'helpers/conversation_helper.dart';

export 'conversation/conversation_utils.dart';

export 'media/media_utils.dart';
export 'media/audio_handler.dart';

/// Returns the initials of a given name.
///
/// The initials are generated by taking the first character of each word in the name,
/// up to a maximum of two initials.
String getInitials(String name) => name.isNotEmpty
    ? name
        .trim()
        .split(' ')
        .where((element) => element.isNotEmpty)
        .map((l) => l[0])
        .take(2)
        .join()
    : '';
