name: likeminds_chat_flutter
description: The monorepo for LikeMinds Chat SDK Flutter, giving access to all our packages
version: 0.14.1
homepage: "https:likeminds.community"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  melos: ^3.4.0
