name: likeminds_chatbot_flutter_sample
description: "A new Flutter project for testing out just the chatbot capabilities of LikeMinds Chat SDK."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core:

  likeminds_chat_flutter_core: ^0.14.1
  google_fonts: ^6.2.0
  flutter_dotenv: ^5.1.0
  firebase_messaging: ^15.0.3
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.3

dependency_overrides:
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
